#!/bin/bash
## COPYRIGHT 2018 JAYKE PETERS
## TrashDelete Installer

## Set variables
WORKDIR=`dirname $0`
LAUNCHAGS="$3/Users/$USER/Library/LaunchAgents"
PLIST="us.jpits.tradel.plist"
LOCALBIN="/usr/local/bin"
TRADEL="$WORKDIR/tradel"

## Functions
function stop {
	/bin/echo STOPPING LAUNCHAGENTS
	if [ -r $LAUNCHAGS/$PLIST ]; then
		/bin/launchctl unload -w $LAUNCHAGS/$PLIST#statements
		/bin/sleep 1
	else
		removeFiles
	fi
}

function removeFiles {
	if [ -r $LAUNCHAGS/$PLIST ]; then
		/bin/echo REMOVING LAUNCHAGENT
		/bin/rm -rf $LAUNCHAGS/$PLIST
	elif [ -r $LOCALBIN/tradel ]; then
		/bin/echo REMOVING EXECUTABLE
		/bin/rm -rf $LOCALBIN/tradel
	else
		exit 0
	fi

	/bin/sleep 1
}

function placeFile {
	/bin/echo PLACING EMTY FILE IN TRASH
	/usr/bin/touch /Users/$USER/.Trash/FILE.FILE
}

function uninstall {
	stop
	removeFiles
	placeFile
	/bin/sleep 3
}

uninstall