#!/bin/bash
## COPYRIGHT 2018 JAYKE PETERS
## AutoEmptyTrash Package Installer Script

## Set variables
WORKDIR=`dirname "$0"`
LAUNCHAGS="$3/Users/$USER/Library/LaunchAgents"
PLIST="us.jpits.AET.plist"
LOCALBIN="/usr/local/bin"
AET="$WORKDIR/AET"


## Functions
function moveFiles {
	/bin/echo MOVING FILES
	/bin/cp -l $WORKDIR/$PLIST $LAUNCHAGS
	/bin/cp -l $AET $LOCALBIN
}

function install {
	moveFiles
	start
}

install